spring.application.name=shortener

spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=admin
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create

url.expiration-days=7
url.short-code-length=8

cors.allowed-origin=${CORS_ALLOWED_ORIGIN}
